# Generated by Django 5.0.1 on 2024-02-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_order_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mecanico', 'Mecanico'), ('Flotas', 'Flotas'), ('Insumos', 'Insumos'), ('Herramienta', 'Herramienta'), ('Electricos', 'Electricos')], max_length=20, null=True),
        ),
    ]
