# Generated by Django 5.0.6 on 2024-05-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_order_date_alter_order_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Estudiante', 'Estudiante'), ('Registro_Control', 'Registro_Control'), ('Credito_Cartera', 'Credito_Cartera'), ('Paz_Salvo', 'Paz_Salvo')], max_length=20, null=True, verbose_name='Categoria'),
        ),
    ]
