# Generated by Django 5.0.6 on 2024-05-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre Usuario'),
        ),
    ]
